OnlineTestProject/OnlineTestProject/Controllers/OnlineTestController.cs
//using System;
//using System.Collections.Generic;
//using System.IO;
//using System.Linq;
//using System.Web;
//using System.Web.Mvc;
//using Newtonsoft.Json;
//using System.Collections.Concurrent;
//using System.Collections;
//using System.Data.SqlClient;
//using System.Configuration;
//using System.Data;
//
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using System.Data.SqlClient;
using System.Configuration;
using System.Data;
using OnlineTestProject.Models;
using System.Collections.Concurrent;
using System.Collections;
using System.Data.OleDb;
using System.Web.Security;
using OnlineTestProject.Controllers;
namespace OnlineTestProject.Controllers
{
    public class OnlineTestController : Controller
    {
        //
        // GET: /OnlineTest/

        public ActionResult OnlineTestView()
        {

            return View();

        }


        OnlineTestProjectEntities dbcontext = new OnlineTestProjectEntities();

        public JsonResult AdminLogin(string email, string pwd)
        {

            //var admin = dbcontext.AdminInfoes.FirstOrDefault(a => a.EmailId == email && a.Pass_word == pwd);
            var admin2 = dbcontext.Adminlogin(email, pwd).FirstOrDefault(a => a.EmailId == email && a.Pass_word == pwd);

            var message = "";
            if (admin2.AdminId > 0)
            {

                return Json(admin2, message = "Login Successful", JsonRequestBehavior.AllowGet);
            }

            else
            {
                return Json(message = "Login Failed", JsonRequestBehavior.AllowGet);
            }


        }

        public ActionResult QuestionCreation()
        {
            return View();
        }


        //this method used storeprocedure//
        //public JsonResult SaveSubjetcs(string SUB)
        //{

        //    dbcontext.storesubjects(SUB);
        //    return Json("success");
        //}

        //this method used to get values from table//
        public JsonResult SaveSubjetcs(Subjects formData)
        {

            dbcontext.Subjects1.Add(formData);
            dbcontext.SaveChanges();
            return Json("success");

        }

        //this method is used storeprocedure to show subjects//
        //public JsonResult ShowSubjects()
        //{
        //    var SubjectList = dbcontext.showsubjects().ToList();
        //    return Json(SubjectList, JsonRequestBehavior.AllowGet);
        //}

        //this method is used table to show subjects//
        //public JsonResult ShowSubjects()
        //{
        //    var SubjectList = dbcontext.Subjects1.ToList();
        //    return Json(SubjectList, JsonRequestBehavior.AllowGet);
        //}


        ////this method is used table to show subjects using Datatable parameters. this is effective method. always use this method to show a list 
        //from database //

        public JsonResult ShowSubjects(DataTableParameters dT)
        {


            var SubjectList1 = new DataTableResultSet_SubjectList();
            SubjectList1.draw = dT.Draw;
            List<Subjects> SubjectList2 = dbcontext.Subjects1.ToList();
            SubjectList1.recordsTotal = SubjectList2.Count;
            SubjectList1.recordsFiltered = SubjectList2.Count;
            SubjectList1.data = SubjectList2;
            return Json(SubjectList1, JsonRequestBehavior.AllowGet);
        }


        //this method is used storeprocedure to delete a subject//
        //public JsonResult RemoveSubject(int SUBID)
        //{
        //    dbcontext.DeleteSubject(SUBID);

        //    return Json("Success");

        //}

        //this method is used table to delete a subject///
        public JsonResult RemoveSubject(int SUBID)
        {

            var del = dbcontext.Subjects1.Find(SUBID);
            dbcontext.Subjects1.Remove(del);
            dbcontext.SaveChanges();
            return Json("Success");

        }



        public ActionResult SubjecstDropdown()
        {
            var subjectlist = dbcontext.Subjects1.ToList();
            List<SelectListItem> Subj = subjectlist.ConvertAll(a => new SelectListItem() { Text = a.Subject.ToString(), Value = a.SubjectId.ToString() }).ToList();
            ViewData["Subject"] = Subj;
            //return Json(subjectlist, JsonRequestBehavior.AllowGet);
            return View("QuestionCreationPage");

        }

        //public JsonResult StoreQuestions(string QUESTION, string OPTIONS)
        //{
        //    //dbcontext.Questions.Add(QUESTION);
        //    //dbcontext.Options.Add(Options);
        //    //var questions1 = JsonConvert.SerializeObject(QUESTION);

        //    var questions1 = JsonConvert.DeserializeObject<Question>(QUESTION);

        //    optionlist = JsonConvert.DeserializeObject<List<Option>>(OPTIONS);
        //    dbcontext.Questions.Add(questions1);
        //    //dbcontext.Options.AddRange(options2);

        //    foreach (var option in optionlist)
        //    {
        //        dbcontext.Options.Add(option);
        //    }

        //    dbcontext.SaveChanges();
        //    return Json("Success");

        //}


        public JsonResult StoreQuestions(string QUESTION, string OPTIONS)
        {

            var questions1 = JsonConvert.DeserializeObject<Question>(QUESTION);
            questions1.CreatedDate = DateTime.UtcNow;
            dbcontext.Questions.Add(questions1);
            dbcontext.SaveChanges();

            var quesid = questions1.QuestionId;

            var optionlist = JsonConvert.DeserializeObject<List<Option>>(OPTIONS);


            //optionlist.Add(quesid);

            //this method is direct table method////
            //foreach (var option in optionlist)
            //{
            //    //option.Question = questions1;
            //    option.QuestionId = quesid; // Bind QuestionId to the option
            //    dbcontext.Options.Add(option); // Add option to the context
            //    dbcontext.SaveChanges();
            //}


            //this method is storeprocedure method////
            foreach (var option in optionlist)
            {
                //option.Question = questions1;
                option.QuestionId = quesid; // Bind QuestionId to the option

                dbcontext.StoreOptions1(option.SubjectId,option.QuestionId, option.OptionIndex, option.OptionText, option.IsCorrect);
                dbcontext.SaveChanges();
            }



            return Json("Success");
        }


        public ActionResult TestCreationPage()
        {
            return View();
        }


        public JsonResult TestCreation(TestTable Details)
        {
            //var Details = JsonConvert.DeserializeObject<TestTable>(TESTDETAILS);
            Details.CreatedDate = DateTime.UtcNow;

            if (Details.Startdate >= Details.Expirydate)
            {
                return Json("Start date must be earlier than Expiry date.");
            }
            dbcontext.TestTables.Add(Details);
            dbcontext.SaveChanges();

            return Json("Success");

        }

        public JsonResult ListOfTests(DataTableParameters dT)
        {
            //var QuesList = dbcontext.TestTables.ToList();
            var QuesList1 = new DataTableResultSet_TestTableList();
            QuesList1.draw = dT.Draw;
            var QuesList2 = dbcontext.TestTables.ToList();
            QuesList1.recordsTotal = QuesList2.Count;
            QuesList1.recordsFiltered = QuesList2.Count;
            QuesList1.data = QuesList2;
            return Json(QuesList1, JsonRequestBehavior.AllowGet);
        }

        /// this is also one of the method to convert date and time format to jq datatable but this is unwanted code because 
        /// we can change date and time in javascript itself and compare with this method and javascript, javascript is effective and fast
        /// in this method we directly changed the date and time into string and  sent to javascript as string://///////

        //public JsonResult QuestionList()
        //{

        //var QuesList = dbcontext.TestTables.ToList().Select(q => new
        //{
        //    q.TestId,
        //    q.TestName,
        //    CreatedDate = q.CreatedDate.ToString("yyyy-MM-ddTHH:mm:ss"),
        //    Startdate = q.Startdate.ToString("yyyy-MM-ddTHH:mm:ss"),
        //    Duration = q.Duration.HasValue ? q.Duration.Value.ToString() : null,
        //    Expirydate = q.Expirydate.HasValue ? q.Expirydate.Value.ToString("yyyy-MM-ddTHH:mm:ss") : null
        //}).ToList();

        //    //return Json(QuesList, JsonRequestBehavior.AllowGet);
        //}


        public JsonResult RemoveTest(int testid)
        {

            var del = dbcontext.TestTables.Find(testid);
            dbcontext.TestTables.Remove(del);
            dbcontext.SaveChanges();
            //COMMIT NOW
            return Json("Success");



        }

        public JsonResult EditTest(int testid)
        {

            var edit = dbcontext.TestTables.Find(testid);
            return Json(edit, JsonRequestBehavior.AllowGet);

        }


        [HttpPost]
        public JsonResult Update(TestTable upd)
        {
            //var Update1 = JsonConvert.DeserializeObject<TestTable>(upd);
            var update = dbcontext.TestTables.Find(upd.TestId);

            update.TestId = upd.TestId;
            update.TestName = upd.TestName;
            update.Startdate = upd.Startdate;
            update.Duration = upd.Duration;
            update.Expirydate = upd.Expirydate;

            if (update == null)
            {
                return Json(new { success = false, message = "Test not found." }, JsonRequestBehavior.AllowGet);
            }

            dbcontext.Entry(update).State = EntityState.Modified; // Set the state to Modified
            dbcontext.SaveChanges();

            return Json(new { success = true, message = "Success" }, JsonRequestBehavior.AllowGet);

        }

OnlineTestProject/OnlineTestProject/Views/OnlineTest/OnlineTestView.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>OnlineTestView</title>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.7.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/OnlineTestJS.js"></script>

</head>
<body>
   <div class="container">
       <form id="Loginform">
       <div class="row">
           <div class="col-md-3"></div>
           <div class="col-md-4">
        @Html.Label("","Email")
        @Html.TextBox("Email", "", new { @class = "form-control", type ="email"})<br />
        @Html.Label("","Password")
        @Html.TextBox("pwd", "", new { @class = "form-control", type="password"})<br />
              <button type="submit" class="btn btn-success" >Login</button>
               </div>
           <div class="col-md-5"></div>
           </div>
           </form>
       </div>
    
</body>
</html>

OnlineTestProject/OnlineTestProject/Views/OnlineTest/QuestionCreation.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>QuestionCreation</title>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.7.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
   @* <script src="~/Scripts/dataTables.min.js"></script>*@
    <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
    <link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
    <script src="~/OnlineTestJS.js"></script>



</head>
<body>
   

    <div class="container">
         <div class="rows">
            <div class="col-3"></div>
             <div class="col-6">
        @Html.Label("","Enter Subject")
        @Html.TextBox("subjects","", new{@class= "form-control mt-3"})<br />
        <button type="button" class="btn btn-warning" onclick="SaveSub()">Save</button>
    </div>
             <div class="col-3"></div>
     </div>
        </div>
    <br />

    <div class="container">
       <div class="rows ">
           <div class="col-md-3"></div>
           <div class="col-md-6">
             <table id="sub" class ="table table-striped table-bordered">
              <thead>
               <tr>
                   <th class="text-center">SubjectId</th>
                   <th class="text-center">Subjects</th>
                   <th class="text-center">Edit</th>
                   <th class="text-center">Delete</th>
               </tr>
                  
           </thead>
            </table>
               </div>
           <div class="col-md-3"></div>
         </div>
        </div>
              
      <a href ="/OnlineTest/SubjecstDropdown">
    <button type="button"  class="btn btn-warning">Next</button><br /><br />
   </a>

    @* <button type="button"  onclick="Next();" class="btn btn-warning">Next</button><br /><br />*@
    @*<button type="button" onclick="location.href='@Url.Action("QuestionCreationPage", "OnlineTest")'"  class ="btn btn-warning"> Nex</button>*@

   

     @*@Html.DropDownList("ProdDropDown", (IEnumerable<SelectListItem>)TempData["Product"], new { @class = "form-select mb-3" })<br />*@

    <div  class="container">

       @* @Html.TextBox("Question", "", new { @class = "form-control" })<br />*@
      
    </div>


</body>
</html>

OnlineTestProject/OnlineTestProject/Views/OnlineTest/QuestionCreationPage.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>QuestionCreationPage</title>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.7.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/OnlineTestJS.js"></script>
</head>
<body>
    <div>
        <div class="container">
        <h3>Welcome To Question CreationPage Admin</h3>
        <br />
        <div class="rows">
            <div class="col-md-2"></div>
            <div class="col-md-2">
                @Html.Label("", "Choose Subject")
                @Html.DropDownList("Subjects", (IEnumerable<SelectListItem>)ViewData["Subject"], new { @class = "form-select"})

                <br />
                <br />
             
            </div>
            
            <div class="col-md-6">
                  @* <textarea class="form-control" id="questions" name="questions" rows="4" cols="50"></textarea>**@
                  @Html.Label("", "Enter Question:")
                @Html.TextArea("Question", "", new { @class = "form-control", @rows = 4, @cols = 50, required = "required" })<br />

                <form id ="Options" name="Options">
                      @Html.Label("", "Enter Options:")
                @Html.TextBox("IndexA", "A", new { @class = "form-control", })<br />

                @Html.TextBox("Option1", "", new { @class = "form-control", @placeholder = "Option1"})<br />

                     @Html.TextBox("IndexB", "B", new { @class = "form-control" })<br />

                @Html.TextBox("Option2", "", new { @class = "form-control", @placeholder = "Option2" })<br />

                     @Html.TextBox("IndexC", "C", new { @class = "form-control" })<br />

                @Html.TextBox("Option3", "", new { @class = "form-control" , @placeholder = "Option3"})<br />

                     @Html.TextBox("IndexD", "D", new { @class = "form-control" })<br />

                @Html.TextBox("Option4", "", new { @class = "form-control", @placeholder = "Option4" })<br />

                     @Html.TextBox("AnsIndex", "", new { @class = "form-control" , @placeholder = "AnswerIndex"})<br />

                @Html.TextBox("Answer", "", new { @class = "form-control", @placeholder = "Answer" })  <br /> 
                    </form>            
               <button type="button" class="btn btn-warning" onclick="Submit()">Submit</button>

            </div>
              <br /> 
            <div class="col-md-2">

         <a href ="/OnlineTest/TestCreationPage">
    <button type="button"  class="btn btn-danger">CreateTest</button><br /><br />
   </a>
            </div>
        </div>
    </div>
        </div>
</body>
</html>

OnlineTestProject/OnlineTestProject/Views/OnlineTest/QuestionViewAndSelectionPage.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>QuestionViewAndSelectionPage</title>
    <script src="~/scripts/bootstrap.min.js"></script>
   <script src="~/scripts/bootstrap.bundle.min.js"></script>
   <link href="~/content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/scripts/jquery-3.7.1.min.js"></script>
    <script src="~/scripts/jquery.validate.min.js"></script>
    <script src="~/scripts/datatables/jquery.datatables.min.js"></script>
    <link href="~/content/datatables/css/jquery.datatables.min.css" rel="stylesheet" />
    <script src="~/Scripts/moment.min.js"></script>
    <script src="~/OnlineTestJS.js"></script>
</head>
<body>
    
        <div class="container mt-4">
             <div class="row">
            <div class="col-md-2">
               
                 @Html.Label("", "Select TestType")
                @Html.DropDownList("Test", (IEnumerable<SelectListItem>)ViewData["TestList"],"Select Test", new { @class = "form-select"})  

                 @Html.Label("", "Choose Subject")
                @Html.DropDownList("Subjects", (IEnumerable<SelectListItem>)ViewData["Subject"],"Choose Subject", new { @class = "form-select"})

                @*@Html.DropDownList("Subjects", new SelectList(ViewData["SubjectList"], "SubjectId", "SubjectName"), "Choose a Subject", new { @class = "form-select" })*@

            </div>  
                 <br />
                 <br />
                 <div class="col-md-8"> 
        
        <table id="Questionlist" class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>SUBJECTID</th>
                 <th>QUESTIONID</th>
                <th>QUESTION</th>
                <th>CREATED DATE</th>
                <th>CHOOSE</th>
                <th>EDIT</th>
                <th>DELETE</th>
            </tr>
                </thead>
            <tbody></tbody>
        </table>
                      <button type="button" class="btn btn-primary" onclick="MakeTest()">SaveQuestions</button><br />   
        </div>
                 <div class="col-md-2">

                     <button type="button" class=" btn btn-success" >QuestionList</button> <br /> 
                 </div>
        </div>  
            </div>   
    
</body>
</html>

OnlineTestProject/OnlineTestProject/Views/OnlineTest/TestCreationPage.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>TestCreationPage</title>

    <script src="~/scripts/bootstrap.min.js"></script>
   <script src="~/scripts/bootstrap.bundle.min.js"></script>
   <link href="~/content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/scripts/jquery-3.7.1.min.js"></script>
    <script src="~/scripts/jquery.validate.min.js"></script>
    <script src="~/scripts/datatables/jquery.datatables.min.js"></script>
    <link href="~/content/datatables/css/jquery.datatables.min.css" rel="stylesheet" />
    <script src="~/Scripts/moment.min.js"></script>

     @*<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>*@

   @*<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">*@
     
    <script src="~/OnlineTestJS.js"></script>
</head>
<body>
       
    <div class="container">
       <div class="row">
        <div class="col-md-3"></div>
           <div class="col-md-6">
        <h3>Welcome to Test CreationPage Admin:</h3>
        <br />
        <br />
        <form id="Createtest" name="Createtest">
            @Html.Label("", "Enter TestName:")

            @Html.TextBox("TestName", "", new { @class = "form-control" })<br />

            @Html.Label("", "Enter StartDate:")

            @Html.TextBox("Startdate", "", new { @class = "form-control", type = "date" })<br />

            @Html.Label("", "Set Duration:")<br />

            <input type="text"  id="duration" name="duration" required pattern="[0-9]{2}:[0-9]{2}" value="00:00" title="Write a duration in the format hh:mm"><br />
            <br /><br />

           @* <input type="text" id="duration" name="duration" required pattern="([0-1][0-9]|2[0-3]):[0-5][0-9]" value="00:00" title="Write a duration in the format hh:mm">*@


            @* @Html.TextBox("Duration", "", new { @class = "form-control", required pattern = "[0-9]{2}:[0-9]{2}" })<br />*@

            @Html.Label("", "Enter ExpiryDate")
            @Html.TextBox("ExpiryDate", "", new { @class = "form-control", type = "date" })<br />

            <button type="button" class=" btn btn-success" onclick="Create()">Create</button>
            <button type="button" class="btn btn-primary" onclick="TestList()">TestList</button><br />
            <a href ="/OnlineTest/SelectTestTypeDropdown">
            <button type="button" class=" btn btn-success" >QuestionList</button> <br />    
                </a>      
        </form>
       
        
</div>
           <div class="col-md-3"></div>
</div>
        </div>
    <br />
    <div class="container">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-8">
        <table id="Testlist" class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>TESTNAME</th>
                <th>CREATED DATE</th>
                <th>STARTDATE</th>
                <th>DURATION</th>
                <th>EXPIRYDATE</th>
                <th>EDIT</th>
                <th>DELETE</th>
            </tr>
                </thead>
            <tbody></tbody>
        </table>
                </div>
</div>
       </div>   
    <br />
    <br />
    <div class="container">
    <div id="testmodify" style="display: none;">
 
        <div class="row">
            <div class="col-md-3"></div>
                        

                     <form id="testmodification" name="testmodification">
             @Html.Hidden("TestId", "", new { @class = "form-control" })

            @Html.Label("", "enter testname:")

            @Html.TextBox("TestName", "", new { @class = "form-control" })<br />

            @Html.Label("", "enter startdate:")

            @Html.TextBox("Startdate", "", new { @class = "form-control", type = "date" })<br />

            @Html.Label("", "set duration:")<br />

            <input type="text"  id="Duration" name="Duration" required pattern="[0-9]{2}:[0-9]{2}" value="00:00" title="Write a duration in the format hh:mm"><br />
            <br /><br />

            @Html.Label("", "Enter ExpiryDate")
            @Html.TextBox("Expirydate", "", new { @class = "form-control", type = "date" })<br />

           @*<button type="button" id="hide" class=" btn btn-success" >Hide</button>  *@
          
            <button type="button" class=" btn btn-success" onclick="Update()">Update</button><br /><br />
                                                               
        </form>
      
        </div>
        </div>
</div>
         
</body>
</html>